### ISSUE TITLE
Replace with unicode-rs/unicode-script?

### ISSUE THREAD

**Issue by Manishearth** [servo/unicode-script#6]
I recently wrote https://github.com/unicode-rs/unicode-script , which does everything this crate does as well as supporting the `Script_Extension` property (and some operations on it), which Rust needs for https://github.com/rust-lang/rust/issues/55467

Would people mind if I archived this repository and continued development in unicode-rs? The new crate is somewhat of a breaking change, but not much, and there are very few consumers so I can just make pull requests and do a major version bump.

cc @SimonSapin @mbrubeck

**Comment by Manishearth** [comment]
unicode-rs/unicode-script _is_ using a currently-beta feature but that will be fixed eventually

My understanding is that this crate hasn't changed much so current users of 0.3.0 can continue using it, whereas we can develop the unicode-rs one into a mature crate as version 0.4.0 onwards.

**Comment by mbrubeck** [comment]
Sounds fine to me.
